default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.14
    hooks:
      # Sync dependencies
      - id: uv-sync
        args: ["--locked", "--all-packages"]
      # Update the uv lockfile
      - id: uv-lock
      # Export to requirements.txt
      - id: uv-export
  - repo: local
    hooks:
    - id: ruff-format
      name: ruff format
      entry: ruff format --force-exclude
      language: unsupported
      types: [python]
      args: []
      require_serial: true
