[project]
name = "sphinx-revealjs-slides"
version = "0.1.0"
description = "Sphinx extensions and a theme for creating Reveal.js slides"
authors = [
    "Ashley Trinh <ashley.trinh@hackbrightacademy.com>"
]
readme = "README.md"
requires-python = ">=3.12,<4"
packages = [
    { include = "sphinx_revealjs_slides", from = "src" }
]
dependencies = [
    "sphinx>=6, <8"
]

[dependency-groups]
dev = [
    "mypy",
    "ruff",
    "pytest",
    "pre-commit",
]
