name: Publish to Pypi
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.12
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
